name: Security Scan

on:
  push:
    branches:
      - main
      - dev

jobs:
  security-scan:
    runs-on: ubuntu-24.04

    env:
      CODESEER_VERSION: v10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Pull CodeSeer Image
      #   run: docker pull ghcr.io/grigorescustefan/codeseer:${CODESEER_VERSION}

      - name: Run CodeSeer
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/input \
            -v ${{ github.workspace }}/reports:/output \
            ghcr.io/grigorescustefan/codeseer:${CODESEER_VERSION}

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/
